spring:
  application:
    name: mcp-server-weather
  ai:
    mcp:
      server:
        name: weather-mcp-server
        version: 1.0.0
        protocol: STREAMABLE

server:
  port: 32180

api:
  key: ${AMAP_API_KEY:ea7733c48f513881ca52791f08c0f9b1}

logging:
  level:
    io.modelcontextprotocol.spec: ERROR
